version: '3.1'
services:
  postgresql:
    container_name: postgresql
    image: postgres:10.4
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "golos"
      POSTGRES_PASSWORD: "golos"
      POSTGRES_DB: "golos"
    volumes:
      - ./data/docker/postgresql/data:/var/lib/postgresql/data
      - ./data/postgresql:/docker-entrypoint-initdb.d
  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui
    ports:
      - 8081:8080
    environment:
      API_URL: "http://localhost:8080/swagger.json"
